version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: docprocessing-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
